### ISSUE TITLE
Build / publish wheels on Appveyor

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zc.FileStorage#1]
Checklist from https://github.com/zopefoundation/zope.proxy/issues/24:

- [ ] a copy of `appveyor.yml` from `zope.interface` or similar
- [ ] someone with an Appveyor account (e.g. @mgedmin ) to enable this project
- [ ] encrypted PyPI upload credentials in the `appveyor.yml` (no change required from the copy in `zope.interface` if @mgedmin is the one who enables the Appveyor account)
- [ ] grant **zope.wheelbuilder** PyPI rights
- [ ] push the `appveyor.yml` commit to master
- [ ] (optionally) a push of a temporary branch that builds and uploads `zc.FileStorage 1.2.0` wheels

**Comment by dataflake** [comment]
@tseaver @jimfulton  Is this package still alive and in use? If yes, please add ``dataflake`` as additional owner for the ``zc.FileStorage`` package on PyPI and I'll set it up.

**Comment by tseaver** [comment]
I've got no clue how / where the package is used.  @jimfulton is the only owner on PyPI.  I think I created this issue in response to a punchlist from somebody else (maybe @icemac?) on packages needing binary wheels.

**Comment by jamadden** [comment]
This package uses the system call `posix_fadvise` so I would be surprised if it compiles on Windows. 

It also doesn’t support python 3.

**Comment by jimfulton** [comment]
Some notes:

- This was written to help scale packing at ZC.  Obviously, ZC isn't using it any more.
- IDK if anyone else is using it. It has value for Py2 on linux.
- Rather than porting it Py3, it should eventually be harvested to improve FS pack.
- Rather than using fadvise, it would have been smarter to memory-map the file. IDK what the implications of that would be for Windows. IDK if it matters. :)

Main benefits:
- Most work is done in separate process, so less starvation of main process.
- fadvise to avoid trashing disk cache (again mmap would have been better)
- Better pack algorithm.

Limitations:
- No GC, because zc.zodbdgc and because I think it's better to pack and gc separately.

Eventually, I'd like to redo packing and GC.

**Comment by dataflake** [comment]
I suggest this issue be closed for now. The actual need for Windows wheels is unclear and no one knows if it even compiles there.

**Comment by icemac** [comment]
Closing issue as suggested by @dataflake.
